### ISSUE TITLE
How to get userID and pushToken?

### ISSUE THREAD

**Issue by vadimwe** [MSakamaki/ngx-onesignal#20]
#### I am submitting a

- [x] Feature Request

#### What is the expected behavior?
Get userId and pushToken

#### Which versions are you using for the following packages?

Angular: 9.1.2
Angular CDK:
Angular CLI: latest
Nx (option):
ngx-onesignal: latest

**Comment by hiramreyes06** [comment]
Me too, I can't find how to get user data.... I saw a lot methods to get it, I tried using de OneSingal object in window object, but I can't use their methods always return undefined. Then with the service of this package has push method but never works, return that it can't find a .then of a promise... So how can I use push method of this package correctly, please I need help.

**Comment by MSakamaki** [comment]
ngx-onesignal v8.0.3 has been released.
https://www.npmjs.com/package/ngx-onesignal ...

The following points have been added, see the sample code.

1. Added Observer and property of userId$.
https://github.com/MSakamaki/ngx-onesignal/blob/master/src/app/app.component.html#L6 ...

2. onPush works.
https://github.com/MSakamaki/ngx-onesignal/blob/master/src/app/app.component.ts

The ngxOnesignal method is not available until OneSignal has been initialized. (That includes the global OneSignal functionality)
But right now we have not been able to detect the end of the initialization.
Therefore we need to know when the loading is complete.
This feature will be added in the next release.

@vadimwe 
It would be helpful if you could tell me about pushToken.

Do I need a method to get a pushToken for OneSignal on the web?
Unfortunately, I checked the official SDK, but I couldn't find that information.
https://documentation.onesignal.com/docs/web-push-sdk

**Comment by MSakamaki** [comment]
add supported v8.0.4 for monitor subscribe status
https://github.com/MSakamaki/ngx-onesignal/blob/master/src/app/app.component.html#L10

**Comment by MSakamaki** [comment]
I are temporarily closing this issue.
please contact us again if have a problem.
