### ISSUE TITLE
Not compatible with Angular Ivy

### ISSUE THREAD

**Issue by bkrajendra** [MSakamaki/ngx-onesignal#45]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
I have installed as per instructions
Should work properly.
#### What is the current behavior?
When I import NgxOneSignalModule I get this error related to not compatible with Angular Ivy

![image](https://user-images.githubusercontent.com/994083/96018993-8de6cc00-0e69-11eb-97f2-0a0e35db88ba.png)

#### What are the steps to reproduce?
Try to install it with Angular 10+

#### Which versions are you using for the following packages?

Angular: 10.1.2
Angular CDK: 10.1.2
Angular CLI: 10.1.2
Nx (option):
ngx-onesignal: 0.0.7

**Comment by MSakamaki** [comment]
I'll get to work on the investigation immediately.
I will also be adding support for Angular v10 for this purpose.

**Comment by MSakamaki** [comment]
@bkrajendra 
[ngx-onesignal@10](https://www.npmjs.com/package/ngx-onesignal), a version with support for angular 10 (and 9), has been released.

It installed on Angular 10 (Ivy) in my environment and is working fine.
please let me know if you have any problems.

Thanks!

**Comment by bkrajendra** [comment]
@MSakamaki 
thanks for the update and quick solution. I have tried it and its working fine. At least all errors are gone after the update.
I will update after checking all functionalities.

**Comment by MSakamaki** [comment]
I are temporarily closing this issue.
please contact us again if have a problem.
