### ISSUE TITLE
How to send tags?

### ISSUE THREAD

**Issue by shimatai** [MSakamaki/ngx-onesignal#9]
Hi,

I need to send tags using this module. I've found the method `this.onesignal.send(method: OneSignalStubFuncionList, value: undefined)` but I don't know how to send a tag using this method.

Can you post an example using the `.push(...)` method?

**Comment by vmdao** [comment]
I think contribute more it

**Comment by MSakamaki** [comment]
@shimatai 
Thank you for reporting!
push Added push function with second parameter.
Check for the latest version 8.0.1.

It should be possible to do it as follows  (sorry,  a disruptive change).

```ts
ngxOneSignal.push(['sendTag', 'key', 'value', function(tagsSent) {
  // Callback called when tags have finished sending
}]);
```

@vmdao 
issues and PR are welcome if there are more features you need.

**Comment by hiramreyes06** [comment]
Can you give us a example using the push method of OneSignalService, it has a that method. I have been trying to use it but always I get a error that says: can;t find then of promise ... I tried with callbacaks too but the arguments are saved in ngxOneSignal object in window object for that I can't get user data and one signal functions... Please
